import { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.agenda': 'Agenda',
    'nav.properties': 'Properties',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview',
    'dashboard.todayJobs': "Today's Jobs",
    'dashboard.noJobsToday': 'No jobs scheduled for today',
    'dashboard.upcomingJobs': 'Upcoming Jobs',
    'dashboard.greeting': 'Hello',
    'dashboard.startJob': 'Start',
    'dashboard.viewJob': 'View',
    'dashboard.goodMorning': 'Good Morning',
    'dashboard.goodAfternoon': 'Good Afternoon',
    'dashboard.goodEvening': 'Good Evening',
    'dashboard.active': 'Active',
    'dashboard.scheduled': 'Scheduled',
    'dashboard.done': 'Done',
    'dashboard.weeklyProgress': 'Weekly Progress',
    'dashboard.cleaningsCompleted': 'cleanings completed',
    'dashboard.nextCleaning': 'Next Cleaning',
    'dashboard.in': 'In',
    'dashboard.now': 'Now',
    
    // Agenda
    'agenda.title': 'Agenda',
    'agenda.subtitle': 'Schedule',
    'agenda.today': 'Today',
    'agenda.month': 'Month',
    'agenda.week': 'Week',
    'agenda.day': 'Day',
    'agenda.addJob': 'Add Job',
    'agenda.noJobs': 'No jobs scheduled',
    'agenda.jobs': 'jobs',
    'agenda.legend': 'Legend',
    'agenda.pending': 'Pending',
    'agenda.inProgress': 'In Progress',
    'agenda.completed': 'Completed',
    'agenda.scheduled': 'Scheduled',
    
    // Properties
    'properties.title': 'Properties',
    'properties.subtitle': 'Manage Locations',
    'properties.addProperty': 'Add Property',
    'properties.noProperties': 'No properties found',
    'properties.bedrooms': 'Bedrooms',
    'properties.bathrooms': 'Bathrooms',
    'properties.searchPlaceholder': 'Search properties...',
    'properties.manage': 'Manage',
    'properties.active': 'Active',
    'properties.today': 'Today',
    'properties.all': 'All',
    'properties.maintenance': 'Maintenance',
    'properties.occupied': 'Occupied',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Account',
    'settings.earnings': 'Earnings History',
    'settings.earningsDesc': 'View your income',
    'settings.team': 'Team',
    'settings.addMember': 'Add Member',
    'settings.notifications': 'Notifications',
    'settings.notificationsDesc': 'Manage alerts',
    'settings.privacy': 'Privacy & Security',
    'settings.privacyDesc': 'Account protection',
    'settings.help': 'Help & Support',
    'settings.helpDesc': 'Get assistance',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your language',
    'settings.logout': 'Log Out',
    'settings.calendar': 'Calendar Sync',
    'settings.calendarDesc': 'Sync jobs with external calendars',
    'settings.calendarLink': 'Calendar Link',
    'settings.calendarLinkDesc': 'Subscribe to this URL in Google Calendar, Apple Calendar, or Outlook',
    'settings.copyLink': 'Copy Link',
    'settings.linkCopied': 'Link copied!',
    'settings.generateLink': 'Generate Link',
    
    // Login
    'login.welcome': 'Welcome',
    'login.join': 'Join',
    'login.signIn': 'Sign in to continue',
    'login.createWorkspace': 'Create your workspace',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.submit': 'Sign In',
    'login.createAccount': 'Create Account',
    'login.loading': 'Loading...',
    'login.noAccount': "Don't have an account? Sign Up",
    'login.hasAccount': 'Already have an account? Sign In',
    
    // Execution - General
    'execution.beforePhotos': 'Before Photos',
    'execution.checklist': 'Checklist',
    'execution.inventory': 'Inventory Check',
    'execution.afterPhotos': 'After Photos',
    'execution.damages': 'Damage Report',
    'execution.summary': 'Summary',
    'execution.complete': 'Complete Job',
    'execution.cancel': 'Cancel',
    'execution.next': 'Next',
    'execution.back': 'Back',
    'execution.takePhoto': 'Take Photo',
    'execution.uploadPhoto': 'Upload Photo',
    
    // Execution - Header
    'exec.cleaningNow': 'Cleaning Now',
    'exec.exitJob': 'Exit Job?',
    'exec.exitDescription': 'Your progress will be saved, but the job will not be marked as completed. You can resume later.',
    'exec.keepWorking': 'Keep Working',
    'exec.exit': 'Exit',
    
    // Execution - Stepper
    'exec.step.beforePhotos': 'Before',
    'exec.step.checklist': 'Tasks',
    'exec.step.damages': 'Damages',
    'exec.step.inventory': 'Inventory',
    'exec.step.afterPhotos': 'After',
    'exec.step.summary': 'Summary',
    
    // Execution - Photo Capture
    'exec.photo.beforeTitle': 'Before Photos',
    'exec.photo.afterTitle': 'After Photos',
    'exec.photo.beforeDesc': 'Capture the current state before cleaning',
    'exec.photo.afterDesc': 'Document your completed work',
    'exec.photo.addPhoto': 'Add Photo',
    'exec.photo.photosCaptured': 'photo(s) captured',
    'exec.photo.minimum': 'minimum',
    'exec.photo.continue': 'Continue',
    'exec.photo.skip': 'Skip this step',
    'exec.photo.uploaded': 'Uploaded',
    'exec.photo.uploadedDesc': 'Photos uploaded successfully',
    'exec.photo.uploadFailed': 'Some photos failed to upload',
    'exec.photo.invalidFile': 'Invalid file type',
    'exec.photo.optimizing': 'Optimizing...',
    'exec.photo.uploading': 'Uploading...',
    
    // Execution - Checklist
    'exec.checklist.title': 'Cleaning Checklist',
    'exec.checklist.tasks': 'tasks',
    'exec.checklist.of': 'of',
    'exec.checklist.remaining': 'remaining',
    'exec.checklist.pause': 'Pause',
    'exec.checklist.nextRoom': 'Next Room',
    'exec.checklist.finalize': 'Finish',
    
    // Execution - Damage Report
    'exec.damage.title': 'Damage Report',
    'exec.damage.subtitle': 'Record any issues found during cleaning',
    'exec.damage.newRecord': 'New Record',
    'exec.damage.problemType': 'Problem Type',
    'exec.damage.severity': 'Severity',
    'exec.damage.description': 'Description',
    'exec.damage.descPlaceholder': 'Describe the problem found...',
    'exec.damage.photo': 'Photo (optional)',
    'exec.damage.add': 'Add',
    'exec.damage.cancel': 'Cancel',
    'exec.damage.register': 'Register Issue',
    'exec.damage.noDamages': 'No damages recorded. If there are no issues, continue to the next step.',
    'exec.damage.typeFurniture': 'Damaged Furniture',
    'exec.damage.typeElectronics': 'Defective Electronics',
    'exec.damage.typeStain': 'Persistent Stain',
    'exec.damage.typeOther': 'Other',
    'exec.damage.severityLow': 'Low',
    'exec.damage.severityMedium': 'Medium',
    'exec.damage.severityHigh': 'High',
    
    // Execution - Inventory
    'exec.inventory.title': 'Inventory',
    'exec.inventory.subtitle': 'Record items used during cleaning',
    'exec.inventory.lowStock': 'Low Stock',
    'exec.inventory.available': 'Available',
    'exec.inventory.used': 'used',
    'exec.inventory.noItems': 'No inventory items registered',
    
    // Execution - Summary
    'exec.summary.greatJob': 'Great Job!',
    'exec.summary.reviewSummary': 'Review the cleaning summary',
    'exec.summary.duration': 'Duration',
    'exec.summary.tasks': 'Tasks',
    'exec.summary.before': 'Before',
    'exec.summary.after': 'After',
    'exec.summary.photos': 'photos',
    'exec.summary.damagesRecorded': 'Damages Recorded',
    'exec.summary.lowStock': 'Low Stock',
    'exec.summary.photoDocumentation': 'Photo Documentation',
    'exec.summary.addNote': 'Add Note (optional)',
    'exec.summary.notePlaceholder': 'Issues, special notes or feedback...',
    'exec.summary.serviceValue': 'Service Value',
    'exec.summary.downloadPdf': 'Download PDF Report',
    'exec.summary.generatingPdf': 'Generating PDF...',
    'exec.summary.complete': 'Complete',
    'exec.summary.more': 'more',
    'exec.summary.lostFoundRecorded': 'Lost & Found Items',
    'exec.summary.pdfPreview': 'Report Preview',
    'exec.summary.generatingPreview': 'Generating preview...',
    'exec.summary.noPdfAvailable': 'No PDF available',
    'exec.summary.previewNote': 'Review the report before downloading',
    'exec.summary.previewPdf': 'Preview PDF',
    
    // Execution - Lost and Found
    'exec.step.lostFound': 'Found',
    'exec.lostFound.title': 'Lost & Found',
    'exec.lostFound.subtitle': 'Document any items found during cleaning',
    'exec.lostFound.newItem': 'New Item',
    'exec.lostFound.description': 'Item Description',
    'exec.lostFound.descPlaceholder': 'Describe the item found...',
    'exec.lostFound.location': 'Location Found',
    'exec.lostFound.locationPlaceholder': 'e.g., Under the bed, Living room sofa...',
    'exec.lostFound.photo': 'Photo (recommended)',
    'exec.lostFound.addItem': 'Add Found Item',
    'exec.lostFound.noItems': 'No items found. If nothing was found, continue to the next step.',
    
    // Job Status
    'status.scheduled': 'Scheduled',
    'status.inProgress': 'In Progress',
    'status.completed': 'Completed',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.back': 'Back',
    'common.continue': 'Continue',
    
    // Finance
    'finance.title': 'Earnings',
    'finance.subtitle': 'History',
    'finance.total': 'Total Earnings',
    'finance.thisMonth': 'This Month',
    'finance.jobs': 'Jobs',
    
    // Reports
    'nav.reports': 'Reports',
    'reports.subtitle': 'Client Dossiers',
    'reports.pendingGeneration': 'Pending Generation',
    'reports.generate': 'Generate',
    'reports.generated': 'Report generated successfully!',
    'reports.errorGenerating': 'Error generating report',
    'reports.published': 'Report published! Share the link with your client.',
    'reports.linkCopied': 'Link copied to clipboard!',
    'reports.deleted': 'Report deleted',
    'reports.empty': 'No reports yet. Complete a cleaning job to generate your first report.',
    'reports.statusPublished': 'Published',
    'reports.statusDraft': 'Draft',
    'reports.publish': 'Publish',
    'reports.copyLink': 'Copy Link',
    
    // Job Form
    'jobForm.title': 'New Job',
    'jobForm.property': 'Property',
    'jobForm.date': 'Date',
    'jobForm.time': 'Time',
    'jobForm.assignTo': 'Assign To',
    'jobForm.notes': 'Notes',
    
    // Job Modal
    'jobModal.title': 'Schedule New Job',
    'jobModal.description': 'Create a new cleaning job with property and time details.',
    'jobModal.create': 'Create Job',
    
    // Property Modal
    'propertyModal.title': 'Add New Property',
    'propertyModal.photo': 'Property Photo',
    'propertyModal.addPhoto': 'Add Photo',
    'propertyModal.basicInfo': 'Basic Information',
    'propertyModal.name': 'Property Name',
    'propertyModal.address': 'Address',
    'propertyModal.type': 'Type',
    'propertyModal.status': 'Status',
    'propertyModal.serviceType': 'Service Type',
    'propertyModal.propertyDetails': 'Property Details',
    'propertyModal.beds': 'Beds',
    'propertyModal.baths': 'Baths',
    'propertyModal.sqft': 'Sqft',
    'propertyModal.basePrice': 'Base Price',
    'propertyModal.accessInfo': 'Access Information',
    'propertyModal.accessCode': 'Access Code',
    'propertyModal.wifiPassword': 'WiFi Password',
    'propertyModal.suppliesLocation': 'Supplies Location',
    'propertyModal.notes': 'Notes',
    'propertyModal.specialInstructions': 'Special Instructions',
    'propertyModal.addProperty': 'Add Property',
    'propertyModal.addedTitle': 'Property Added',
    'propertyModal.addedDescription': '{name} has been added successfully.',
    
    // Property Details View
    'propertyDetails.title': 'Property Details',
    'propertyDetails.beds': 'Beds',
    'propertyDetails.baths': 'Baths',
    'propertyDetails.sqft': 'Sqft',
    'propertyDetails.status': 'Status',
    'propertyDetails.propertyType': 'Property Type',
    'propertyDetails.serviceType': 'Service Type',
    'propertyDetails.basePrice': 'Base Price',
    'propertyDetails.standardRate': 'Standard cleaning rate',
    'propertyDetails.noPrice': 'No price set',
    'propertyDetails.lastCleaned': 'Last Cleaned',
    'propertyDetails.statusReady': 'Ready',
    'propertyDetails.statusNeedsCleaning': 'Needs Cleaning',
    'propertyDetails.statusOccupied': 'Occupied',
    'propertyDetails.typeApartment': 'Apartment',
    'propertyDetails.typeHouse': 'House',
    'propertyDetails.typeVilla': 'Villa',
    'propertyDetails.typeLoft': 'Loft',
    'propertyDetails.typeStudio': 'Studio',
    'propertyDetails.serviceHouseCleaning': 'House Cleaning',
    'propertyDetails.serviceDeepCleaning': 'Deep Cleaning',
    'propertyDetails.serviceAirbnbCleaning': 'Airbnb Cleaning',
    'propertyDetails.serviceMoveInOut': 'Move in/Out',
    'propertyDetails.serviceRecurringCleaning': 'Recurring Cleaning',
    'propertyDetails.serviceCommercialCleaning': 'Commercial Cleaning',
    'propertyDetails.serviceOfficeCleaning': 'Office Cleaning',
    'propertyDetails.servicePostConstruction': 'Post Construction',
    
    // Room Management
    'rooms.title': 'Rooms',
    'rooms.subtitle': 'Property rooms and spaces',
    'rooms.add': 'Add Room',
    'rooms.empty': 'No rooms added yet',
    'rooms.name': 'Room Name',
    'rooms.size': 'Size (sqft)',
    'rooms.notes': 'Notes',
    'rooms.type.bedroom': 'Bedroom',
    'rooms.type.bathroom': 'Bathroom',
    'rooms.type.kitchen': 'Kitchen',
    'rooms.type.living_room': 'Living Room',
    'rooms.type.dining_room': 'Dining Room',
    'rooms.type.office': 'Office',
    'rooms.type.laundry': 'Laundry',
    'rooms.type.garage': 'Garage',
    'rooms.type.other': 'Other',
    
    // Checklist Template Editor
    'checklist.title': 'Cleaning Checklist',
    'checklist.tasks': 'tasks',
    'checklist.useDefault': 'Use Default',
    'checklist.addSection': 'Add Section',
    'checklist.newSectionPlaceholder': 'New section name...',
    'checklist.newTaskPlaceholder': 'New task...',
    'checklist.photoRequired': 'Photo required',
    'checklist.noPhoto': 'No photo required',
    'checklist.resetToDefault': 'Reset to default',
    'checklist.usingDefault': 'Using default checklist template',
    'checklist.selectPreset': 'Select preset...',
    'checklist.editTask': 'Edit task',
    'checklist.preset.standard': 'Standard Clean',
    'checklist.preset.airbnb': 'Airbnb Turnover',
    'checklist.preset.deepClean': 'Deep Clean',
    'checklist.preset.moveInOut': 'Move In/Out',
    'checklist.preset.recurring': 'Recurring Clean',
    'checklist.preset.postConstruction': 'Post Construction',
    'checklist.preset.commercial': 'Commercial Clean',
    
    // Profile
    'profile.edit': 'Edit Profile',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.photo': 'Photo',
    'profile.changePhoto': 'Change Photo',
    'profile.updated': 'Profile Updated',
    'profile.updatedDesc': 'Your information has been saved',
    
    // Purification
    'dashboard.purification': 'PURIFICATION',
    
    // Dashboard KPI & Actions
    'dashboard.thisMonth': 'This Month',
    'dashboard.totalJobs': 'Jobs',
    'dashboard.satisfaction': 'Rating',
    'dashboard.pending': 'Pending',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.newJob': 'New',
    'dashboard.property': 'Property',
    'dashboard.report': 'Report',
    'dashboard.team': 'Team',
    'dashboard.today': 'Today',
    'dashboard.viewAgenda': 'See all',
    'dashboard.continue': 'Continue',
    'dashboard.progress': 'Progress',
    'jobs.startChecklist': 'Start Checklist',
  },
  pt: {
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.agenda': 'Agenda',
    'nav.properties': 'Propriedades',
    'nav.settings': 'Configurações',
    
    // Dashboard
    'dashboard.title': 'Painel',
    'dashboard.subtitle': 'Visão Geral',
    'dashboard.todayJobs': 'Trabalhos de Hoje',
    'dashboard.noJobsToday': 'Nenhum trabalho agendado para hoje',
    'dashboard.upcomingJobs': 'Próximos Trabalhos',
    'dashboard.greeting': 'Olá',
    'dashboard.startJob': 'Iniciar',
    'dashboard.viewJob': 'Ver',
    'dashboard.goodMorning': 'Bom Dia',
    'dashboard.goodAfternoon': 'Boa Tarde',
    'dashboard.goodEvening': 'Boa Noite',
    'dashboard.active': 'Ativos',
    'dashboard.scheduled': 'Agendados',
    'dashboard.done': 'Concluídos',
    'dashboard.weeklyProgress': 'Progresso Semanal',
    'dashboard.cleaningsCompleted': 'limpezas concluídas',
    'dashboard.nextCleaning': 'Próxima Limpeza',
    'dashboard.in': 'Em',
    'dashboard.now': 'Agora',
    
    // Agenda
    'agenda.title': 'Agenda',
    'agenda.subtitle': 'Cronograma',
    'agenda.today': 'Hoje',
    'agenda.month': 'Mês',
    'agenda.week': 'Semana',
    'agenda.day': 'Dia',
    'agenda.addJob': 'Adicionar Trabalho',
    'agenda.noJobs': 'Nenhum trabalho agendado',
    'agenda.jobs': 'jobs',
    'agenda.legend': 'Legenda',
    'agenda.pending': 'Pendente',
    'agenda.inProgress': 'Em andamento',
    'agenda.completed': 'Concluído',
    'agenda.scheduled': 'Agendado',
    
    // Properties
    'properties.title': 'Propriedades',
    'properties.subtitle': 'Gerenciar Locais',
    'properties.addProperty': 'Adicionar Propriedade',
    'properties.noProperties': 'Nenhuma propriedade encontrada',
    'properties.bedrooms': 'Quartos',
    'properties.bathrooms': 'Banheiros',
    'properties.searchPlaceholder': 'Buscar propriedades...',
    'properties.manage': 'Gerenciar',
    'properties.active': 'Ativas',
    'properties.today': 'Hoje',
    'properties.all': 'Todas',
    'properties.maintenance': 'Manutenção',
    'properties.occupied': 'Ocupadas',
    
    // Settings
    'settings.title': 'Configurações',
    'settings.subtitle': 'Conta',
    'settings.earnings': 'Histórico de Ganhos',
    'settings.earningsDesc': 'Veja sua renda',
    'settings.team': 'Equipe',
    'settings.addMember': 'Adicionar Membro',
    'settings.notifications': 'Notificações',
    'settings.notificationsDesc': 'Gerenciar alertas',
    'settings.privacy': 'Privacidade e Segurança',
    'settings.privacyDesc': 'Proteção da conta',
    'settings.help': 'Ajuda e Suporte',
    'settings.helpDesc': 'Obter assistência',
    'settings.language': 'Idioma',
    'settings.languageDesc': 'Escolha seu idioma',
    'settings.logout': 'Sair',
    'settings.calendar': 'Sincronizar Calendário',
    'settings.calendarDesc': 'Sincronize jobs com calendários externos',
    'settings.calendarLink': 'Link do Calendário',
    'settings.calendarLinkDesc': 'Assine esta URL no Google Calendar, Apple Calendar ou Outlook',
    'settings.copyLink': 'Copiar Link',
    'settings.linkCopied': 'Link copiado!',
    'settings.generateLink': 'Gerar Link',
    
    // Login
    'login.welcome': 'Bem-vindo',
    'login.join': 'Cadastrar',
    'login.signIn': 'Entre para continuar',
    'login.createWorkspace': 'Crie seu espaço de trabalho',
    'login.email': 'E-mail',
    'login.password': 'Senha',
    'login.submit': 'Entrar',
    'login.createAccount': 'Criar Conta',
    'login.loading': 'Carregando...',
    'login.noAccount': 'Não tem uma conta? Cadastre-se',
    'login.hasAccount': 'Já tem uma conta? Entre',
    
    // Execution - General
    'execution.beforePhotos': 'Fotos Antes',
    'execution.checklist': 'Lista de Verificação',
    'execution.inventory': 'Verificar Inventário',
    'execution.afterPhotos': 'Fotos Depois',
    'execution.damages': 'Relatório de Danos',
    'execution.summary': 'Resumo',
    'execution.complete': 'Concluir Trabalho',
    'execution.cancel': 'Cancelar',
    'execution.next': 'Próximo',
    'execution.back': 'Voltar',
    'execution.takePhoto': 'Tirar Foto',
    'execution.uploadPhoto': 'Enviar Foto',
    
    // Execution - Header
    'exec.cleaningNow': 'Limpando Agora',
    'exec.exitJob': 'Sair do Trabalho?',
    'exec.exitDescription': 'Seu progresso será salvo, mas o trabalho não será marcado como concluído. Você pode retomar depois.',
    'exec.keepWorking': 'Continuar Trabalhando',
    'exec.exit': 'Sair',
    
    // Execution - Stepper
    'exec.step.beforePhotos': 'Antes',
    'exec.step.checklist': 'Tarefas',
    'exec.step.damages': 'Danos',
    'exec.step.inventory': 'Estoque',
    'exec.step.afterPhotos': 'Depois',
    'exec.step.summary': 'Resumo',
    
    // Execution - Photo Capture
    'exec.photo.beforeTitle': 'Fotos Antes',
    'exec.photo.afterTitle': 'Fotos Depois',
    'exec.photo.beforeDesc': 'Capture o estado atual antes da limpeza',
    'exec.photo.afterDesc': 'Documente seu trabalho concluído',
    'exec.photo.addPhoto': 'Adicionar Foto',
    'exec.photo.photosCaptured': 'foto(s) capturada(s)',
    'exec.photo.minimum': 'mínimo',
    'exec.photo.continue': 'Continuar',
    'exec.photo.skip': 'Pular etapa',
    'exec.photo.uploaded': 'Enviado',
    'exec.photo.uploadedDesc': 'Fotos enviadas com sucesso',
    'exec.photo.uploadFailed': 'Algumas fotos falharam no envio',
    'exec.photo.invalidFile': 'Tipo de arquivo inválido',
    'exec.photo.optimizing': 'Otimizando...',
    'exec.photo.uploading': 'Enviando...',
    
    // Execution - Checklist
    'exec.checklist.title': 'Lista de Tarefas',
    'exec.checklist.tasks': 'tarefas',
    'exec.checklist.of': 'de',
    'exec.checklist.remaining': 'restante(s)',
    'exec.checklist.pause': 'Pausar',
    'exec.checklist.nextRoom': 'Próxima Sala',
    'exec.checklist.finalize': 'Finalizar',
    
    // Execution - Damage Report
    'exec.damage.title': 'Registro de Danos',
    'exec.damage.subtitle': 'Registre problemas encontrados durante a limpeza',
    'exec.damage.newRecord': 'Novo Registro',
    'exec.damage.problemType': 'Tipo de Problema',
    'exec.damage.severity': 'Severidade',
    'exec.damage.description': 'Descrição',
    'exec.damage.descPlaceholder': 'Descreva o problema encontrado...',
    'exec.damage.photo': 'Foto (opcional)',
    'exec.damage.add': 'Adicionar',
    'exec.damage.cancel': 'Cancelar',
    'exec.damage.register': 'Registrar Problema',
    'exec.damage.noDamages': 'Nenhum dano registrado. Se não houver problemas, continue para a próxima etapa.',
    'exec.damage.typeFurniture': 'Móvel Danificado',
    'exec.damage.typeElectronics': 'Eletrônico com Defeito',
    'exec.damage.typeStain': 'Mancha Persistente',
    'exec.damage.typeOther': 'Outro',
    'exec.damage.severityLow': 'Baixa',
    'exec.damage.severityMedium': 'Média',
    'exec.damage.severityHigh': 'Alta',
    
    // Execution - Inventory
    'exec.inventory.title': 'Inventário',
    'exec.inventory.subtitle': 'Registre os itens utilizados na limpeza',
    'exec.inventory.lowStock': 'Estoque Baixo',
    'exec.inventory.available': 'Disponível',
    'exec.inventory.used': 'usado',
    'exec.inventory.noItems': 'Nenhum item de inventário cadastrado',
    
    // Execution - Summary
    'exec.summary.greatJob': 'Excelente Trabalho!',
    'exec.summary.reviewSummary': 'Revise o resumo da limpeza',
    'exec.summary.duration': 'Duração',
    'exec.summary.tasks': 'Tarefas',
    'exec.summary.before': 'Antes',
    'exec.summary.after': 'Depois',
    'exec.summary.photos': 'fotos',
    'exec.summary.damagesRecorded': 'Danos Registrados',
    'exec.summary.lowStock': 'Estoque Baixo',
    'exec.summary.photoDocumentation': 'Documentação Fotográfica',
    'exec.summary.addNote': 'Adicionar Observação (opcional)',
    'exec.summary.notePlaceholder': 'Problemas, notas especiais ou feedback...',
    'exec.summary.serviceValue': 'Valor do Serviço',
    'exec.summary.downloadPdf': 'Baixar Relatório PDF',
    'exec.summary.generatingPdf': 'Gerando PDF...',
    'exec.summary.complete': 'Concluir',
    'exec.summary.more': 'mais',
    'exec.summary.lostFoundRecorded': 'Achados e Perdidos',
    'exec.summary.pdfPreview': 'Pré-visualização do Relatório',
    'exec.summary.generatingPreview': 'Gerando pré-visualização...',
    'exec.summary.noPdfAvailable': 'PDF não disponível',
    'exec.summary.previewNote': 'Revise o relatório antes de baixar',
    'exec.summary.previewPdf': 'Visualizar PDF',
    
    // Execution - Lost and Found
    'exec.step.lostFound': 'Achados',
    'exec.lostFound.title': 'Achados e Perdidos',
    'exec.lostFound.subtitle': 'Registre itens encontrados durante a limpeza',
    'exec.lostFound.newItem': 'Novo Item',
    'exec.lostFound.description': 'Descrição do Item',
    'exec.lostFound.descPlaceholder': 'Descreva o item encontrado...',
    'exec.lostFound.location': 'Local Encontrado',
    'exec.lostFound.locationPlaceholder': 'ex: Debaixo da cama, Sofá da sala...',
    'exec.lostFound.photo': 'Foto (recomendado)',
    'exec.lostFound.addItem': 'Adicionar Item Encontrado',
    'exec.lostFound.noItems': 'Nenhum item encontrado. Se nada foi encontrado, continue para a próxima etapa.',
    
    // Job Status
    'status.scheduled': 'Agendado',
    'status.inProgress': 'Em Andamento',
    'status.completed': 'Concluído',
    
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.add': 'Adicionar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.all': 'Todos',
    'common.back': 'Voltar',
    'common.continue': 'Continuar',
    
    // Finance
    'finance.title': 'Ganhos',
    'finance.subtitle': 'Histórico',
    'finance.total': 'Ganhos Totais',
    'finance.thisMonth': 'Este Mês',
    'finance.jobs': 'Trabalhos',
    
    // Reports
    'nav.reports': 'Relatórios',
    'reports.subtitle': 'Dossiês do Cliente',
    'reports.pendingGeneration': 'Pendentes de Geração',
    'reports.generate': 'Gerar',
    'reports.generated': 'Relatório gerado com sucesso!',
    'reports.errorGenerating': 'Erro ao gerar relatório',
    'reports.published': 'Relatório publicado! Compartilhe o link com seu cliente.',
    'reports.linkCopied': 'Link copiado!',
    'reports.deleted': 'Relatório excluído',
    'reports.empty': 'Nenhum relatório ainda. Complete uma limpeza para gerar seu primeiro relatório.',
    'reports.statusPublished': 'Publicado',
    'reports.statusDraft': 'Rascunho',
    'reports.publish': 'Publicar',
    'reports.copyLink': 'Copiar Link',
    
    // Job Form
    'jobForm.title': 'Novo Trabalho',
    'jobForm.property': 'Propriedade',
    'jobForm.date': 'Data',
    'jobForm.time': 'Horário',
    'jobForm.assignTo': 'Atribuir A',
    'jobForm.notes': 'Observações',
    
    // Job Modal
    'jobModal.title': 'Agendar Novo Trabalho',
    'jobModal.description': 'Crie um novo trabalho de limpeza com detalhes da propriedade e horário.',
    'jobModal.create': 'Criar Trabalho',
    
    // Property Modal
    'propertyModal.title': 'Adicionar Nova Propriedade',
    'propertyModal.photo': 'Foto da Propriedade',
    'propertyModal.addPhoto': 'Adicionar Foto',
    'propertyModal.basicInfo': 'Informações Básicas',
    'propertyModal.name': 'Nome da Propriedade',
    'propertyModal.address': 'Endereço',
    'propertyModal.type': 'Tipo',
    'propertyModal.status': 'Status',
    'propertyModal.serviceType': 'Tipo de Serviço',
    'propertyModal.propertyDetails': 'Detalhes da Propriedade',
    'propertyModal.beds': 'Quartos',
    'propertyModal.baths': 'Banheiros',
    'propertyModal.sqft': 'M²',
    'propertyModal.basePrice': 'Preço Base',
    'propertyModal.accessInfo': 'Informações de Acesso',
    'propertyModal.accessCode': 'Código de Acesso',
    'propertyModal.wifiPassword': 'Senha WiFi',
    'propertyModal.suppliesLocation': 'Local dos Suprimentos',
    'propertyModal.notes': 'Notas',
    'propertyModal.specialInstructions': 'Instruções Especiais',
    'propertyModal.addProperty': 'Adicionar Propriedade',
    'propertyModal.addedTitle': 'Propriedade Adicionada',
    'propertyModal.addedDescription': '{name} foi adicionada com sucesso.',
    
    // Property Details View
    'propertyDetails.title': 'Detalhes da Propriedade',
    'propertyDetails.beds': 'Quartos',
    'propertyDetails.baths': 'Banheiros',
    'propertyDetails.sqft': 'M²',
    'propertyDetails.status': 'Status',
    'propertyDetails.propertyType': 'Tipo de Propriedade',
    'propertyDetails.serviceType': 'Tipo de Serviço',
    'propertyDetails.basePrice': 'Preço Base',
    'propertyDetails.standardRate': 'Taxa padrão de limpeza',
    'propertyDetails.noPrice': 'Nenhum preço definido',
    'propertyDetails.lastCleaned': 'Última Limpeza',
    'propertyDetails.statusReady': 'Pronto',
    'propertyDetails.statusNeedsCleaning': 'Precisa Limpeza',
    'propertyDetails.statusOccupied': 'Ocupado',
    'propertyDetails.typeApartment': 'Apartamento',
    'propertyDetails.typeHouse': 'Casa',
    'propertyDetails.typeVilla': 'Villa',
    'propertyDetails.typeLoft': 'Loft',
    'propertyDetails.typeStudio': 'Estúdio',
    'propertyDetails.serviceHouseCleaning': 'Limpeza Residencial',
    'propertyDetails.serviceDeepCleaning': 'Limpeza Profunda',
    'propertyDetails.serviceAirbnbCleaning': 'Limpeza Airbnb',
    'propertyDetails.serviceMoveInOut': 'Mudança',
    'propertyDetails.serviceRecurringCleaning': 'Limpeza Recorrente',
    'propertyDetails.serviceCommercialCleaning': 'Limpeza Comercial',
    'propertyDetails.serviceOfficeCleaning': 'Limpeza de Escritório',
    'propertyDetails.servicePostConstruction': 'Pós Construção',
    
    // Room Management
    'rooms.title': 'Cômodos',
    'rooms.subtitle': 'Cômodos e espaços da propriedade',
    'rooms.add': 'Adicionar Cômodo',
    'rooms.empty': 'Nenhum cômodo adicionado ainda',
    'rooms.name': 'Nome do Cômodo',
    'rooms.size': 'Tamanho (m²)',
    'rooms.notes': 'Observações',
    'rooms.type.bedroom': 'Quarto',
    'rooms.type.bathroom': 'Banheiro',
    'rooms.type.kitchen': 'Cozinha',
    'rooms.type.living_room': 'Sala de Estar',
    'rooms.type.dining_room': 'Sala de Jantar',
    'rooms.type.office': 'Escritório',
    'rooms.type.laundry': 'Lavanderia',
    'rooms.type.garage': 'Garagem',
    'rooms.type.other': 'Outro',
    
    // Checklist Template Editor
    'checklist.title': 'Lista de Limpeza',
    'checklist.tasks': 'tarefas',
    'checklist.useDefault': 'Usar Padrão',
    'checklist.addSection': 'Adicionar Seção',
    'checklist.newSectionPlaceholder': 'Nome da nova seção...',
    'checklist.newTaskPlaceholder': 'Nova tarefa...',
    'checklist.photoRequired': 'Foto obrigatória',
    'checklist.noPhoto': 'Sem foto obrigatória',
    'checklist.resetToDefault': 'Restaurar padrão',
    'checklist.usingDefault': 'Usando lista de tarefas padrão',
    'checklist.selectPreset': 'Selecionar preset...',
    'checklist.editTask': 'Editar tarefa',
    'checklist.preset.standard': 'Limpeza Padrão',
    'checklist.preset.airbnb': 'Airbnb Turnover',
    'checklist.preset.deepClean': 'Limpeza Profunda',
    'checklist.preset.moveInOut': 'Mudança',
    'checklist.preset.recurring': 'Limpeza Recorrente',
    'checklist.preset.postConstruction': 'Pós Construção',
    'checklist.preset.commercial': 'Limpeza Comercial',
    
    // Profile
    'profile.edit': 'Editar Perfil',
    'profile.name': 'Nome',
    'profile.email': 'E-mail',
    'profile.phone': 'Telefone',
    'profile.role': 'Cargo',
    'profile.photo': 'Foto',
    'profile.changePhoto': 'Alterar Foto',
    'profile.updated': 'Perfil Atualizado',
    'profile.updatedDesc': 'Suas informações foram salvas',
    
    // Purification
    'dashboard.purification': 'PURIFICAÇÃO',
    
    // Dashboard KPI & Actions
    'dashboard.thisMonth': 'Mês',
    'dashboard.totalJobs': 'Jobs',
    'dashboard.satisfaction': 'Nota',
    'dashboard.pending': 'Pendente',
    'dashboard.quickActions': 'Ações',
    'dashboard.newJob': 'Novo',
    'dashboard.property': 'Imóvel',
    'dashboard.report': 'Dossiê',
    'dashboard.team': 'Equipe',
    'dashboard.today': 'Hoje',
    'dashboard.viewAgenda': 'Ver tudo',
    'dashboard.continue': 'Continuar',
    'dashboard.progress': 'Progresso',
    'jobs.startChecklist': 'Iniciar',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
