// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxafpoydheganjeuktuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4YWZwb3lkaGVnYW5qZXVrdHVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0NDIyOTUsImV4cCI6MjA4NTAxODI5NX0.UgICetB6vA4WKtUn4zzkGpXVBhFJpBjkaQKifyFs9fM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});