// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouzxkijkhkmjvnhaswhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91enhraWpraGttanZuaGFzd2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTg3ODEsImV4cCI6MjA2NDk3NDc4MX0.sb_publishable_VqVAWFhYr-2Fbp0USu1f2g_zwl319Id";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});